### ISSUE TITLE
Add mappings for description values in Filings data

### ISSUE THREAD

**Issue by turowicz** [LiberisLabs/CompaniesHouse.NET#11]
There is an undocumented field that is required so that we can display correct descriptions of each filing.

The field is `description_values`

**Comment by kevbite** [comment]
Do we have a few examples of what is returned? Just to give us an idea of how to model it?

**Comment by turowicz** [comment]
I left it as a comment to your comment on the PR

**Comment by turowicz** [comment]
`descrpition_values` is a json object, not an array, dictionary or scalar. It can be anything therefore we have to return it as the full jobject and use dynamic dispatch to grab the values for text formatting.
