### ISSUE TITLE
Officer Summary always null

### ISSUE THREAD

**Issue by turowicz** [LiberisLabs/CompaniesHouse.NET#13]
The library is not retrieving Officer Summary or the Officer list.

@kevbite are you guys aware of this?

**Comment by turowicz** [comment]
I'm going to add it - should it be a separate client or another HTTP call in the Profile client?

**Comment by kevbite** [comment]
Looks like it should be pulled with the company profile - `officer_summary` - https://developer.companieshouse.gov.uk/api/docs/company/company_number/companyProfile-resource.html
Feel free to add it if its not included. 

There is however a officers list which has more details - https://developer.companieshouse.gov.uk/api/docs/company/company_number/officers/officerList.html

**Comment by turowicz** [comment]
@kevbite added the /officers endpoint - it is always guaranteed to return data while company profile's officer summary is optional.

**Comment by kevbite** [comment]
I'm busy in meetings all afternoon but I've got @Blundell89 to check this over and merge it in for you.

**Comment by turowicz** [comment]
thanks!
