### ISSUE TITLE
CompanyType 'uk-establishment' - 'Newtonsoft.Json.JsonSerializationException'

### ISSUE THREAD

**Issue by Amith211** [LiberisLabs/CompaniesHouse.NET#23]
It appears there is a relatively new **CompanyType** called **'uk-establishment'**.
You might find [this post](http://forum.aws.chdev.org/t/uk-establishments/597) useful:

This results in the following in VS:
An exception of type **'Newtonsoft.Json.JsonSerializationException'** ...

Additional: Error converting value **"uk-establishment"** to **type** **'LiberisLabs.CompaniesHouse.Response.CompanyType'. Path 'items[2].company_type'**

I used the **CompanySearch** with query text as 'British Gas'.

Cheers.

**Comment by kevbite** [comment]
Seems like the API docs online differ from the actual possible enum list here too - https://github.com/companieshouse/api-enumerations/blob/master/constants.yml

**Comment by kevbite** [comment]
Fixed in version 2.4.6 https://www.nuget.org/packages/CompaniesHouse/1.4.6
