### ISSUE TITLE
CompanyStatus 'closed' - 'Newtonsoft.Json.JsonSerializationException'

### ISSUE THREAD

**Issue by Amith211** [LiberisLabs/CompaniesHouse.NET#24]
I not sure whether this ought to be a separate issue or not. See Also Issue #23.

When using the same query as before (**CompanySearch** with query text as 'British Gas')
I'm also getting the following:

An exception of type **'Newtonsoft.Json.JsonSerializationException'**

Additional: Error converting value **"closed"** to **type** **'LiberisLabs.CompaniesHouse.Response.CompanyStatus'. Path 'items[2].company_status'**

Thanks

**Comment by kevbite** [comment]
Thanks for raising, this issue has now been fixed in version 2.4.5 - https://www.nuget.org/packages/CompaniesHouse/1.4.5
