### ISSUE TITLE
Implement Filings

### ISSUE THREAD

**Issue by turowicz** [LiberisLabs/CompaniesHouse.NET#6]
Ability to list all filings with appropriate descriptions from:

https://github.com/companieshouse/api-enumerations/blob/master/filing_history_descriptions.yml

**Comment by kevbite** [comment]
Hello,
Listing the filing history seems fine but not sure we should be putting UI concerns within this API wrapper, these should be implemented in your UI layer based on the enum values that the wrapper returns. If you think about localization then this makes more sense to be in the UI layer within your application.

**Comment by turowicz** [comment]
@kevbite you are absolutely right - I meant the API call to get the filings. Actual descriptions are linked for reference (so we don't forget to use them in UI)

**Comment by turowicz** [comment]
Have a look at my PR, it probably makes more sense.

**Comment by turowicz** [comment]
PR #7 all ready to be accepted so this can be resolved
