### ISSUE TITLE
Targeting Hell

### ISSUE THREAD

**Issue by turowicz** [LiberisLabs/CompaniesHouse.NET#9]
Unfortunately my clients are using various versions of .NET and this library only targets 4.5.1.

This issue is to create targets for 4.5, 4.6, and Core (at least).

All files to be included in a single nuget package.

References:
http://blog.marcgravell.com/2015/11/the-road-to-dnxpart-3.html
https://stackoverflow.com/questions/34611829/how-to-package-a-net-framework-library

**Comment by turowicz** [comment]
@kevbite if I create a PR with necessary changes, would you do the Appveyor side?

**Comment by kevbite** [comment]
That's fine, If i remember its a lot hard than it looks from the cover as you also need to re-target the nuget packages being used within the project.

Would a interim release of just knocking down the framework to 4.5 work for you?

**Comment by turowicz** [comment]
Yes - that would be great!

I would save me today :)

side note: a single nuget package can have multiple versions of the library inside, it's supported out of the box, the real problem is producing those dlls. I may have some time over the weekend to do that but knocking the version down do 4.5 would save me today.

**Comment by kevbite** [comment]
I'll sort out bumping down to version 4.5 within the next hour.

**Comment by turowicz** [comment]
@kevbite done - check it out in PR

**Comment by kevbite** [comment]
OK cheers
